Repository cse110-fa21-group15/cse110-fa21-group15, pull requests merged in 2021-12, with the labels that each got.

#58 E2E testing on login and create recipe pages
  __tests__/e2e.test.js
  __tests__/img.jpeg
  __tests__/unit.test.js
  jest-puppeteer.config.cjs
  package-lock.json
  package.json
  source/assets/scripts/firebase.js
Labels: Needs Approval

#65 Modified Recipe Cards
  source/assets/scripts/RecipeCard.js
  source/assets/scripts/main.js
  source/assets/styles/cookbook.css
  source/cookbook.html
  source/index.html
  source/mealplan.html
  source/recipePage.html
  source/recipeUpdate.html
  source/recipeUpload.html
  source/searchresults.html
Labels: enhancement

#67 Sahil api test
  source/assets/scripts/mealplan.js
  source/assets/scripts/search.js
  source/cookbook.html
  source/homepage.html
  source/recipeUpload.html
  source/searchresults.html
Labels: enhancement

#70 Storing Firebase keys in separate file
  source/assets/scripts/api.js
  source/assets/scripts/deleteRecipe.js
  source/assets/scripts/firebase.js
  source/assets/scripts/main.js
  source/assets/scripts/recipeUpdate.js
  source/assets/scripts/recipeUpload.js
Labels: documentation, enhancement

#72 added/fixed documentation comments in js files
  package-lock.json
  source/assets/scripts/RecipeCard.js
  source/assets/scripts/api.js
  source/assets/scripts/createRecipe.js
  source/assets/scripts/deleteRecipe.js
  source/assets/scripts/editRecipe.js
  source/assets/scripts/firebase.js
  source/assets/scripts/main.js
  source/assets/scripts/recipePage.js
  source/assets/scripts/recipeUpdate.js
  source/assets/scripts/recipeUpload.js
  source/assets/scripts/search.js
Labels: documentation

#73 Backend Favorite Recipes function
  source/assets/scripts/deleteRecipe.js
  source/assets/scripts/firebase.js
  source/assets/scripts/main.js
  source/assets/scripts/mealPlan.js
Labels: enhancement

#74 Search and filters
  source/assets/scripts/RecipeCard.js
  source/assets/scripts/RecipeCardSearch.js
  source/assets/scripts/fillRecipePageSpoonacular.js
  source/assets/scripts/search.js
  source/assets/scripts/searchresults.js
  source/assets/styles/searchresults.css
  source/recipePageSpoonacular.html
  source/searchresults.html
Labels: enhancement

#87 Daryl format fix
  source/assets/images/Add.png
  source/assets/images/Delete.png
  source/assets/images/Download.png
  source/assets/images/Edit.png
  source/assets/images/Favorite.png
  source/assets/scripts/RecipeCard.js
  source/assets/scripts/RecipeCardSearch.js
  source/assets/scripts/deleteRecipe.js
  source/assets/scripts/fillRecipePage.js
  source/assets/scripts/fillRecipePageSpoonacular.js
  source/assets/scripts/firebase.js
  source/assets/scripts/main.js
  source/assets/scripts/searchresults.js
  source/assets/styles/cookbook.css
  source/assets/styles/forgotPassword.css
  source/assets/styles/global.css
  source/assets/styles/homepage.css
  source/assets/styles/mealplan.css
  source/assets/styles/recipePage.css
  source/assets/styles/recipeUpload.css
  source/assets/styles/searchresults.css
  source/assets/styles/signIn.css
  source/assets/styles/signUp.css
  source/recipePage.html
Labels: documentation, enhancement

#101 css/html fixes
  source/assets/images/Favorite.png
  source/assets/images/FavoriteFilled.png
  source/assets/styles/cookbook.css
  source/assets/styles/forgotPassword.css
  source/assets/styles/global.css
  source/assets/styles/homepage.css
  source/assets/styles/mealplan.css
  source/assets/styles/recipePage.css
  source/assets/styles/recipeUpload.css
  source/assets/styles/searchresults.css
  source/assets/styles/signIn.css
  source/assets/styles/signUp.css
  source/cookbook.html
  source/recipePage.html
  source/recipeUpdate.html
  source/recipeUpload.html
Labels: documentation, enhancement

#104 Merging Random Recipe with main
  source/assets/scripts/recipeOfDay.js
  source/assets/scripts/search.js
  source/assets/styles/homepage.css
  source/homepage.html
Labels: enhancement

#105 Merging Meal plan with main
  .DS_Store
  source/assets/scripts/dragdrop.js
  source/assets/scripts/mealPlan.js
  source/assets/scripts/mealplan.js
  source/assets/styles/mealplan.css
  source/mealplan.html
  source/searchresults.html
Labels: enhancement

#109 Searchfix
  source/assets/scripts/recipeOfDay.js
  source/assets/scripts/search.js
Labels: bug

#110 Fixed description on recipe card
  source/assets/scripts/RecipeCardSearch.js
  source/assets/scripts/fillRecipePageSpoonacular.js
Labels: enhancement

#111 Recipe of the day image
  source/assets/scripts/fillRecipePageSpoonacular.js
  source/assets/scripts/recipeOfDay.js
  source/mealplan.html
  source/recipePage.html
  source/recipePageSpoonacular.html
  source/recipeUpdate.html
Labels: enhancement

#117 daryl final js fix
  source/assets/scripts/deleteRecipe.js
  source/assets/scripts/fillRecipePageSpoonacular.js
  source/assets/scripts/firebase.js
  source/assets/scripts/main.js
  source/assets/scripts/mealPlan.js
  source/assets/scripts/recipeUpdate.js
  source/assets/scripts/recipeUpload.js
  source/assets/scripts/search.js
  source/assets/styles/mealplan.css
  source/assets/styles/recipeUpload.css
  source/assets/styles/signUp.css
  source/cookbook.html
  source/mealplan.html
  source/searchresults.html
Labels: documentation, enhancement

#118 daryl misc fixes
  source/assets/scripts/fillRecipePageSpoonacular.js
  source/assets/scripts/mealPlan.js
  source/assets/scripts/recipeUpload.js
  source/assets/styles/homepage.css
  source/assets/styles/mealplan.css
  source/assets/styles/recipePage.css
  source/recipePage.html
  source/recipePageSpoonacular.html
  source/signIn.html
Labels: documentation, enhancement

#119 fixed drag from cookbook
  source/assets/scripts/fillRecipePageSpoonacular.js
  source/assets/scripts/mealPlan.js
  source/assets/scripts/search.js
Labels: enhancement

#122 daryl css fix
  source/assets/scripts/RecipeCard.js
  source/assets/scripts/RecipeCardSearch.js
  source/assets/scripts/fillRecipePageSpoonacular.js
  source/assets/styles/homepage.css
Labels: documentation, enhancement

#126 mirai branch fixes + daryl fixes
  .vscode/settings.json
  source/assets/scripts/RecipeCard.js
  source/assets/scripts/RecipeCardSearch.js
  source/assets/styles/homepage.css
  source/assets/styles/mealplan.css
  source/assets/styles/recipePage.css
  source/cookbook.html
  source/forgotPassword.html
  source/homepage.html
  source/index.html
  source/mealplan.html
  source/recipePage.html
  source/recipePageSpoonacular.html
  source/recipeUpdate.html
  source/recipeUpload.html
  source/searchresults.html
  source/signIn.html
  source/signUp.html
Labels: documentation, enhancement

#127 resetting database
  source/assets/scripts/api.js
Labels: enhancement

#128 deleted dead code
  source/assets/scripts/firebase.js
Labels: documentation

#130 One more fix
  source/assets/scripts/fillRecipePageSpoonacular.js
  source/assets/scripts/firebase.js
  source/assets/scripts/main.js
  source/assets/scripts/search.js
  source/signUp.html
Labels: documentation, enhancement

#131 Final API Key for submission
  source/assets/scripts/fillRecipePageSpoonacular.js
  source/assets/scripts/search.js
Labels: documentation
